### ISSUE TITLE
Missing response code validation after performing network operation

### ISSUE THREAD

**Issue by amazuerar** [thebigg73/OpenSongTablet#122]
Dear developer!

My name is Alejandro Mazuera-Rozo, I am a PhD Student at Universidad de los Andes, and at Università della Svizzera italiana. I am part of a research on the usage of network libraries within android apps. As a result of this we identified some code locations that might have network related problems.

In this case, we present the code locations that are related to a missing validation of the response code when performing network operations. When you make an HTTP request, your application should validate the response status code before manipulating it, otherwise it could cause misbehaviour within the app.

In order to address this issue we recommend:

1. To validate the response code to be within the range [200-300], this can be done with `getResponseCode()`
2. To see: https://docs.oracle.com/javase/7/docs/api/java/net/HttpURLConnection.html#getResponseCode()

**Potential Code Location not validating response code:**

https://github.com/thebigg73/OpenSongTablet/blob/8563eeeab9745b42c67e1ab7c779b92fcdf4bf28/app/src/main/java/com/garethevans/church/opensongtablet/PopUpCustomSlideFragment.java#L576-L582

**Comment by thebigg73** [comment]
Fixed in v6 (upcoming)
