### ISSUE TITLE
Chekbox and scrolbar is very close (

### ISSUE THREAD

**Issue by SergKnyz** [thebigg73/OpenSongTablet#137]
Greeting, dear developers.

I have a lot of years use your program and recently clash with the problem when creating a setlist. 
Chekbox for adding songs in set and scrolbar is very close! I often miss the smartphone screen (
Instead of adding a song to the list, the scroll is triggered and I fly away completely to another place. Scrolbar works even, if he is invisible. 

![изображение](https://user-images.githubusercontent.com/29613359/147032752-dd583883-52d9-49dc-addc-3b1c9a262a16.png)

Please, could you upgrade them: Checkbox shift to the left and scrolbar shift to the right?
Or make scrolbar only indicator, because the scrolling of songs and so works perfectly without any scrolbar.
Or is it possible to make scroll inactive when he is invisible? 

With respect to you, Sergey.

**Comment by thebigg73** [comment]
Hi Serg,

Good to hear from you.  Believe it or not there is an update coming with a
relocated fast scroll bar to the left thanks to a recent GitHub
contribution from my regular contributor Ian.  I'm still testing out a few
bits and pieces, but nearly ready for release!

Best wishes,
Gareth

**Comment by SergKnyz** [comment]
Wonderful.
I hope to see it in the nearest release.
Thanks for your work.

**Comment by iv-gha** [comment]
Hello Sergey,

You can see the changes in 5.4.2.  The tick is much easier to click and the quick scroll is now on the left.  Have fun.
