### ISSUE TITLE
Folder selection button always labelled as "select where to save file"

### ISSUE THREAD

**Issue by ZsigE** [thebigg73/OpenSongTablet#15]
First up: thanks so much for creating this, I use it weekly and it's utterly fantastic. I keep meaning to try and contribute!

Now, the bug: when I tap the button at the top of the song selection pane on the left to switch folders, the window that pops up asks me which folder I want to save the current file in. Obviously I don't want to do that, and it took me ages to realise that it wasn't saving anything at all - possible code reuse without changing the explanatory text?

**Comment by thebigg73** [comment]
Hi Philip,

Just about to head out to a gig, but will have a look tomorrow.  I've
attached a screenshot of my device which doesn't have this issue, but I
wonder if you're using and older (pre 5.0) version of android and have a
double header/title.  I would have copied an existing file and modified it,
but probably forgot to change this bit.  Thanks for pointing it out.  I'll
get a fix out later this week.

Gareth

**Comment by thebigg73** [comment]
Yep - it was as you suggested!  Uploading repaired files (I had 3 files with the same issue) and will release to Google Play later this week (waiting for some translation files).
