### ISSUE TITLE
transpose incorrectly

### ISSUE THREAD

**Issue by SergKnyz** [thebigg73/OpenSongTablet#150]
Greetings.
After some of the latest updates, transpositions in the German system broke.
Key "A" , "B" and "H" transposed incorrectly! 

We have:
C - C#/Db - D - D#/Eb - E - F - F#/Gb - G  - G#/Ab - A - B - H 
But should be (by halftons):
C - C#/Db - D - D#/Eb - E - F - F#/Gb - G  - G#/Ab - A - A#/B - H
![изображение](https://user-images.githubusercontent.com/29613359/157713792-bbbfca61-0840-44ce-89b1-5b2fd6fbbe80.png)

Please correct it, because after transposing the song is spoiled.
Upd: I downloaded version 5.4.1 (201) from the site and there is no such problem.  Apparently she appeared later.

**Comment by iv-gha** [comment]
Hello SergKnyz,

I have proposed a change to fix German transpose to give
C - C#/Db - D - D#/Eb - E - F - F#/Gb - G - G#/Ab - A - A#/B - H
and for the other German notation
C - Cis/Des - D - Dis/Es - E - F - Fis/Ges - G - Gis/As - A - Ais/B - H

This should make German transpose behave like before the December update.  That update was to make Transpose faster which makes song changes faster.  It is hard to check that all the formats are working well when you do not use the format! 
Your report is very helpful, thanks.

Hopefully this will fix.

Kind regards
Ian

**Comment by iv-gha** [comment]
Hello again.

v5.4.8 includes fixes for this issue.

If you know all of your songs are in one format then you can set the chord system to respect that.

For German format you can...

OPTIONS > CHORDS > CHOOSE CHORD FORMAT

Set 'Choose your preferred chord format when transposing a song'
to German
C - C#/Db - D - D#/Eb - E - F - F#/Gb - G - G#/Ab - A - A#/B - H

Set 'Always assume original songs are in my preferred chord format' ON.

When using Transpose make sure
Set 'Use preferred chord format' is ON

As these settings force the original song format to be treated as being in German format and force the transpose output to German format, you will have German format in and out.

For anyone who knows all their songs are in one chord format then selecting setting like above (for their chord format) should, for a good original file, give good transpose.

I recommend this issue is closed if no further update from SergKnyz.

Ian

**Comment by SergKnyz** [comment]
Thank you.
I get update.
It seems everything works fine!
just i want to clarify "preferred chord format":
![изображение_viber_2022-04-11_19-03-14-537](https://user-images.githubusercontent.com/29613359/162768908-41e7f935-d6e6-4ad4-89c4-d22b2979f70c.jpg)
"Bb/A#" and "Bbm/A#m" is true for the English system, but in German, we must get the "B/A#"  and "Bm/A#m". 
What do you think?

**Comment by thebigg73** [comment]
![eurochord](https://user-images.githubusercontent.com/7831274/162942670-9fe70fe6-8591-423d-b55e-3384471eb50f.png)
I've updated this in the MaterialApp (upcoming version)

**Comment by thebigg73** [comment]
![eurochord2](https://user-images.githubusercontent.com/7831274/162942988-b08c42bb-ac33-402d-b39c-1fa9a3ac3fa5.png)

**Comment by SergKnyz** [comment]
looks beautiful!
You will allow to use the "Am" type chords, or will be forced to be converted to "a"?

**Comment by thebigg73** [comment]
Hi,

Isn't that the correct way of displaying minor chords for European/German
format?  Like Ian, I don't use this format!

Gareth

**Comment by SergKnyz** [comment]
Hello!
Probably this is a more modern way. maybe it is so. 
But we work with a rather large collection of songs without lowercase letters. 
Usually add simply "m". 
Usually often such songs are found on the Internet. Even I think all sites known to me)
And so I ask whether direct and backward compatibility will continue?

**Comment by SergKnyz** [comment]
Hello, dear developers.
In last versions the problem with the transposition of the some chord is preserved. 
If the option "preferred format" is off, then
1) "H" It is not transposed on any intervals, remains unchanged.
2) "B" (Si-flat in German system) is considered app as  "B" (Si  in English system) and transposed, respectively

although in all cases I choose manually German System.

**Comment by thebigg73** [comment]
Hi Serg,
I actually think the app will cope with this if you set the default as Ian
described.  The app will treat the A... as a major chord and will ignite
the 'm' as an additional party it doesn't know about (as it does for things
like 7, mint, etc.).  If the app sees lowercase minor chords, it will treat
them as such and they will be kept in this format.  Using capital letters,
the app will treat them as major chords and leave them in this format (but
not touch the m).  If you want to send me a song to test it with, feel free.
You should be fine!
