### ISSUE TITLE
Hotfix required: Connect as client not working Android 12 - Missing Android permission

### ISSUE THREAD

**Issue by iv-gha** [thebigg73/OpenSongTablet#159]
Fine Location Permission not requested failure.   This has this been missed and is observed to stop ''connect as a client' on devices Moto G50, Samsumg S22 etc. Android 12 devices.   Reported against 
https://github.com/thebigg73/OpenSongTablet/commit/b7c0287a0f2f843f58a3114125080e01d78f5186

Hi,

After a fresh install on Android 12 I find...

Install of 5.4.9 on Android 12. On first use of Connect Devices prompted

Allow OpenSongApp to find, connect to and determine the relative position of nearby devices?
Allow selected.

Examining OpenSongApp App permissions at this point 'Nearby devices' is 'Allowed' and
Location is 'Not Allowed'

Suggesting the previous Nearby Allow has worked.

Use of Connect devices > Act as client does not result in 'Discover services'.

If manually in OpenSongApp App permissions 'Location' is set 'Allowed', Location access for this app set to 'Allow only while using the app' and 'Use precise locations' is set ON - use of 'Connect devices > Act as client' does result in 'Discover services' and successful connection.

One or more calls made by the app needs fine location permissions on Android 12 for 'Connect devices > Act as client' to work.

Cheers
Ian

**Comment by thebigg73** [comment]
I'll get that added in, although I thought I'd used the correct permissions for each level - wonder if there has been a change in Android/Google?

**Comment by thebigg73** [comment]
The permission request was missing in PresenterMode.
I have added the 'Not used for location' in manifest where fine location was noted to stop this request being 'dangerous' so should now work in Android 12+

**Comment by thebigg73** [comment]
Added to 5.5.2

**Comment by iv-gha** [comment]
Hi Gareth,
Still goes wrong on Android 12 at 5.5.2.  Needs fine location to act as client! Never displays 'Discover services'. Connect is demanding!

Re-open please as not there yet.

Thanks

**Comment by thebigg73** [comment]
The permissions should be the same for host/client.  Google's documentation
is pretty shocking around this.  There are several conflicting guidelines
about what is required.
I've added fine location permissions back for API30-32.  I only have an
emulator to test for Android 12.  Could you let me know if this fixes the
issue please.  I've pushed to beta channel on the Play Store v5.5.3 as I've
added a feature request to alphabetically sort sets which was a simple
enough addition.  It's also pushed to GitHub now

**Comment by iv-gha** [comment]
Hello Gareth,
Android 12 is happy - I have made further comments https://github.com/thebigg73/OpenSongTablet/commit/112348d9b5023b4e789982dfa07e10791ebcf20c#commitcomment-81752305
