### ISSUE TITLE
MaterialApp: Lyrics with single chord in chord line above poor alignment

### ISSUE THREAD

**Issue by thebigg73** [thebigg73/OpenSongTablet#160]
If there is a line with a single chord at the beginning of the line, the lyric line gets indented by one extra space, whereas the chord line is in the correct place.

Notice line 1/2 incorrectly aligned, whereas line 3 is ok
<img width="381" alt="image" src="https://user-images.githubusercontent.com/7831274/180736504-47165df6-7cd2-4a52-9f93-a12b2cb598b6.png">

<img width="242" alt="image" src="https://user-images.githubusercontent.com/7831274/180736808-556b8ae6-2aae-4a24-ad20-4e4012813c00.png">

**Comment by thebigg73** [comment]
@iv-gha Any thoughts on this one.  I've had a look through the code, but I'm struggling to see where the issue is.  It happens with capo and native chords.  This doesn't happen with the master branch (obviously because you did it right!!)

**Comment by iv-gha** [comment]
'Master' consolidated section handling into ProcessSong.prepareSongSections  a while back.

After noting the line types  it will adjust a line with
if (StaticVariables.sectionContents[x][y].length() > 0 && " .;".contains(StaticVariables.sectionContents[x][y].substring(0, 1))) {
        StaticVariables.sectionContents[x][y] = StaticVariables.sectionContents[x][y].substring(1).replaceAll("\\s+$", "");
}
It exits with first char trimmed if it is space, full stop or semi-colon.  It tests for and strips only song line type indicators - just removing a character would break scripture lines etc.  This handles line type indicators in one place.

From what I can see,  MaterialApp handles lines differently.

**Comment by thebigg73** [comment]
Found it!  It was in ProcessSong near the end of the groupTable() logic
`textView.setText((str.replaceAll("[|_]", " ")));`
changed to:
``textView.setText((str.replaceAll("[|_]", " ")).trim());``
