### ISSUE TITLE
MaterialApp: SongSelect only working with chord output (not score)

### ISSUE THREAD

**Issue by thebigg73** [thebigg73/OpenSongTablet#175]

**Comment by iv-gha** [comment]
#220 updates to v5 for lyrics and chords extract.  Lyric / Chords / Sheet download by call of Songselect site buttons is needed in v6.   This is how v5 does 'score' download.

**Comment by thebigg73** [comment]
The click on button to download logic was there but wasn't actually called.  Added now.
