### ISSUE TITLE
[v6 beta2] ignore button on no GSF dialog not responding

### ISSUE THREAD

**Issue by pjvleeuwen** [thebigg73/OpenSongTablet#185]
![Screenshot_20230127-212410](https://user-images.githubusercontent.com/908808/215190748-18ff857b-a905-4cc8-a340-b55b2be85acf.png)

For the 'no GSF warning'-dialog the ignore warning button is not responding. When clicking it flashes, but no other response, dialog stays open. The X close button does work. I got this error first thing after installing the beta2 which was an update of the already installed v5.

**Comment by thebigg73** [comment]
I've fixed this in beta 3.  I'm assuming you don't have Play Services
installed though.  In future, the message will be shown the first time,
clicking ignore will hide that part of the warning and won't show again
unless you clear your cache or reinstall.

Best wishes,
Gareth

**Comment by pjvleeuwen** [comment]
You assume correctly :) thnx for the quick fix. I will test it when I get the beta3
