### ISSUE TITLE
[v6 beta2] "Information" dialog without information

### ISSUE THREAD

**Issue by pjvleeuwen** [thebigg73/OpenSongTablet#186]
![Screenshot_20230128-153449](https://user-images.githubusercontent.com/908808/215273441-cf648f44-a69f-47fa-aa38-6eec39516b32.png)

After editing the app shows an "Information" dialog without information. I have seen it multiple times.

**Comment by thebigg73** [comment]
Grrrr.
That is me being stupid.   Hid thewarning but forgot to disable the popup
of nothing is to be shown.   Guess it'll be beta 4 then!

Thanks for letting me know
Gareth

**Comment by pjvleeuwen** [comment]
Haha. Just to be sure you are not mixing up #185 and this #186 : this new issue is another problem and still on beta2. So this issue is not the result of testen the fix for #185 on beta3.

Just to be sure. Reading your message and the similarities of the issue it seems a mixup might have occurred.

Will you let me know when a new beta is available for testing?

**Comment by pjvleeuwen** [comment]
Oh and I now see I am on the OpenSongTablet project. While I am using OpenSong on a Pixel 6 mobile phone (with GrapheneOS excl GFS). Is this the correct place for mobile phone issues?

**Comment by thebigg73** [comment]
Yeah, this is the correct place.   The app used to be called OpenSong
tablet.   If I change this, I'd need to start as a new app on the play
store.
It will be the same issuein beta 2 and beta 3.   The fix on beta3 just
fixed the ignore warning button and checked for the changing of preferences
better.

Heading off to a gig now, but will look at the code tomorrow
