### ISSUE TITLE
[v6 beta 6] Stage mode song render problems

### ISSUE THREAD

**Issue by iv-gha** [thebigg73/OpenSongTablet#189]
in Stage mode render can

1.  On song change using swipe or song menu, songs may not show all sections.

With layout bounds in use the sections are seen to be present but with zero height - they may or may not have content.  The song will  render properly immediately after the problem if the option menu is opened and closed.

2. On song change - if the previous song has sections with narrow content the same section number in the new song is oversized.

The song will properly display immediately after the problem if the option menu is opened and closed.

**Comment by iv-gha** [comment]
With second screen on - the missing sections can be scroll through and content appears on the second screen.

**Comment by thebigg73** [comment]
Fixed this in beta 7.
I think the issue was the layouts being prepared in ProcessSong.java maybe hadn't quite finished before being drawn to the screen.  I changed the beginning of the drawing/measuring process to a post method on the main view which seems to have sorted this.

**Comment by iv-gha** [comment]
Hello Gareth,
Point 2 looks resolved at beta 9. 
Point 1 is not. Sections can still be missing.
We need a reliable layout engine!  Please consider further.

**Comment by iv-gha** [comment]
Please open this issue as it is not resolved.

**Comment by thebigg73** [comment]
I'm really struggling to see this point 1 on my device.  It was happening along with point 2 before beta 9, but I've not seen it since.  Is this still happening for you?

**Comment by iv-gha** [comment]
It is certainly better, with low freq of error. The challenge is to be certain it is rock solid.  I did see some occurrences with an app version that resolved point 2 well.  Not as frequent so harder to observe .  I think the code needs to validate all is good and if not report the error. Trying to manually catch it might prove tiring and the more we see no errors the more certain we become.

**Comment by iv-gha** [comment]
I suggest we close this at this time.  This was focused on getting good stability for the primary screen display and has achieved that.
