### ISSUE TITLE
[v6 beta 6] Stage mode scroll

### ISSUE THREAD

**Issue by iv-gha** [thebigg73/OpenSongTablet#191]
v5 stage mode scrolls so that the selected section is lower down the screen - the percentage taken from 100% - max section height %.

A user using stage mode to project lyrics, one man band style (me!), will need to move to the next section early to get words projected ahead of need.  Having the previous section displayed is needed.  Please adjust smooth scroll of stage mode sections.

**Comment by iv-gha** [comment]
Hi Gareth,

To add detail...  this is moving through sections using a pedal,  this is the same as clicking a section in stage mode.  In v5 the section does not  smooth scroll to the top but to a point lower if the user has set a max section height of less than 100%.  Cheers.

**Comment by thebigg73** [comment]
I don't think v5 did this intentionally!  It used a linear layout and smooth scrolled to the section.  Android decides how far to scroll so the view is visible.  If the view is bigger than the height available, it will scroll to the top of the page, if smaller, it will scroll enough to make the entire view visible.
v6 moved away from a linearlayout to a custom recyclerview.  Smooth scroll to in a recyclerview is not quite as simple as only the visible views are actually drawn at a time (meaning less memory is wasted on non visible views).  I had to implement a separate scroll function (also complicated by the scaling and pinch to zoom features).
I've updated beta 8 (there was a crash happening in beta 7 on 64 bit devices due to an update in a library used) to not scroll to the chosen section while autoscroll is running - hopefully this makes sense?

**Comment by iv-gha** [comment]
Actually it is intentional and added by commit.  It is not autoscroll related.  It acts to scroll not to the top, specifically so that the previous section can still be seen.  I just could not figure out how to scroll a recycler section to an offset on the screen for v6 - recycler stuff.  It is practical, a musician needing to step to the next section who is self projecting lyrics, can  still be playing the end of the previous section - the feature keeps it on screen above the selected section - result!

**Comment by thebigg73** [comment]
Ah!  I didn't realise that.  I've tweaked the MyRecyclerView (in the customviews folder) to deal with this.
The relevant bit of code that I've tweaked is:

`public void smoothScrollTo(Context c, LayoutManager layoutManager, int position) {
        smoothScroller = new LinearSmoothScroller(c) {
            @Override
            protected int getVerticalSnapPreference() {
                return LinearSmoothScroller.SNAP_TO_END;
            }
            @Override
            protected float calculateSpeedPerPixel(DisplayMetrics displayMetrics) {
                return 100f / displayMetrics.densityDpi;
            }
        };
        smoothScroller.setTargetPosition(position);
        layoutManager.startSmoothScroll(smoothScroller);
    }`

**Comment by thebigg73** [comment]
I've updated the code - hopefully you can see the change in
customviews/MyRecyclerView.java
The main difference is changing SNAP_TO_TOP to SNAP_TO_BOTTOM.
I've also slowed the animation a little to make it easier to follow.  When
autoscrolling, I've left it so the clicking doesn't jump to that section as
it would seriously mess with the autoscrolling!

**Comment by iv-gha** [comment]
The best option is to develop smooth scroll to a screen position as used in v5  A less better option is to scroll the section above the clicked section to the top.  The aim is to show the section within the song with prev and next sections (size permitting) displayed - allowing the chosen section to be seen in context.  Cheers Ian.

**Comment by thebigg73** [comment]
Hi Ian,
I think I've figured this out (or at least a different implementation of it).  Uploading a commit for this now

**Comment by iv-gha** [comment]
Thanks for the good work.  So far so good.  I have put a change in a commit to have the position set from the preference as in v5.

**Comment by iv-gha** [comment]
On my phone the stage mode scroll is using animation, that is the screen is stretching and returning to final position - this should not be enabled.  Move of a top section to position down screen can, when set to 80%, be wrong.  It is getting there.

**Comment by iv-gha** [comment]
The Android stretch effect starts when a manual swipe scroll hits the top or bottom of the scrolled area - the animation then remains active for section click moves within the scroll after that. There must be an option to turn off this system animation.

Also - behaviour when zoomed should be considered.  Do we want to support zoom in Stage mode?  I suspect not.

**Comment by thebigg73** [comment]
I think the issue is the app is selecting the wrong position.  I did notice
this a few times.  This animation happens if you try to scroll above or
below the top/bottom item in the list.

**Comment by iv-gha** [comment]
Yes, It perhaps needs to assess the available height of sections above if
moving down and below if moving up.  These dictate a limit as to how far it
is possible to move in a particular direction.  The animations reflect an
ask to move to an impossible position.

Cheers
Ian

**Comment by iv-gha** [comment]
2 scroll methods are now in use which give good scroll behaviour.  One outstanding consideration is the scroll speeds of these 2 methods - these should be made the same., I do not think they are at the moment.

**Comment by iv-gha** [comment]
A zoomed display does not scroll correctly (v5 too).  I think Pinch zoom should be disabled in Stage mode.
