### ISSUE TITLE
Missing menus

### ISSUE THREAD

**Issue by diancho** [thebigg73/OpenSongTablet#192]
After period of inactivity and use of other applications, all menus are gone.
![Screenshot_20230227_082802_OpenSongApp](https://user-images.githubusercontent.com/42693793/221568676-60d13fdf-d40d-4a0b-8bed-64656b8d0e22.jpg)
![Screenshot_20230227_082747_OpenSongApp](https://user-images.githubusercontent.com/42693793/221568684-b740e84f-37fa-46ef-88f5-2b8704bfe0a7.jpg)

The phone is Samsung Galaxy A12, with Android 13.
Opensongapp v.6.0.0_beta6.

**Comment by thebigg73** [comment]
I think I have a fix ready in beta 7.  Once this has been released, could you check and let me know if this fixes the issue.

**Comment by diancho** [comment]
There is no problem now.  Thank you.

**Comment by diancho** [comment]
Menues are working good.
