### ISSUE TITLE
[v6 beta 10] Not fixed - Capo transpose does not respect preferred key settings for transposing and capo display

### ISSUE THREAD

**Issue by iv-gha** [thebigg73/OpenSongTablet#200]
Capo transpose is not respecting the users choice of flats and sharps in the users preference.

I think v5 transposed the key of the original song and considered it for force of use of flats in transpose.

v6 is using a mini song that does not have key set? It perhaps should be setting the key of the mini song used for a line to the transposed key of the original song?

Also, transposed capo key is not shown in the title and capo information of the song display or in the song editor.  This is needed as it aids users in selecting capo number and knowing the capo key. Maybe this is a v5 thing added after you forked v6.

Cheers
Ian

**Comment by thebigg73** [comment]
Fixed
It turns out the settings page for chord preferences was saving the preferences as pref_Ab, pref_Bb, etc.
The transpose settings was trying to look up prefAb, prefBb, etc (without the underscore).  Doh!

**Comment by thebigg73** [comment]
v6 does not show the capo information in the song title as it uses the capo on screen icon instead.
Do we need both?

**Comment by iv-gha** [comment]
The song details block has single lines which overflow.  We are sensibly using ellipse to indicate overflow.  The UI flow is that the user clicks the Title to access full details (v6 should catch up with v5 and use the song details block style here).

I am thinking you are not a major Capo/Transpose user as the beta started with very evident transpose and render fails.  I use songs from SongSelect, this has a 2 column view that imports as short lines very suitable for full width display and (after adding || splits) for projection as-is.  Legal projection means the Title must be what the copyright holder dictates and these can be long.  On a small screen these will overflow in the song details.

For a small screen user the v6 options for the song details info are, use small font sizes, turn off the battery/clock area and have 0 custom margins.  Even then overflow will occur.  That it occurs is not a failing.

My thinking is that a 10 inch tablet user should not suffer less on screen information because of the constraints of small screens.  I say provide the capo information as this give these users the option to use large fonts and have access to Capo info all the time.  This would mean no demand for a screen touch during performance (hands are best on instruments!) if the Capo info needs to be looked up.

Perhaps we do not force it  - default to having capo info and provide an option to turn it off!  More choice - arrrgh!

**Comment by thebigg73** [comment]
V5 didn't ellipse the capo information on my device in portrait (capo info shows in landscape)

<img width="104" alt="image" src="https://user-images.githubusercontent.com/7831274/228295882-f220fc70-78ae-427d-8da5-3fea2580d392.png">
<img width="81" alt="image" src="https://user-images.githubusercontent.com/7831274/228296116-a60fbf45-c78d-466a-a9a0-cc3932f814d1.png">

**Comment by thebigg73** [comment]
Unhelpfully small screenshots!  Try again...
<img width="275" alt="image" src="https://user-images.githubusercontent.com/7831274/228296775-77c646e1-59f8-461c-bcc7-1b06613bbf4a.png">
<img width="544" alt="image" src="https://user-images.githubusercontent.com/7831274/228297126-65389761-436f-4569-b0af-f5ee21d34462.png">

**Comment by thebigg73** [comment]
Top image is landscape (similar to large screen) and shows capo.  Small screen (or portrait) does not show capo in the title bar (nor does it show ellipsis), but does keep the floating window onscreen.  
In my opinion, the floating window onscreen is far better to understand and seen than the (E) [2 (D)] in the titlebar.  v6 gives users the option of leaving this onscreen at all times, or autohiding (default setting).

![image](https://user-images.githubusercontent.com/7831274/228300362-1467df50-3bf1-4870-b05e-fef789787569.png)

Unfortunately I have missed bugs on v6 beta as they have not been on my radar or use case (I only ever tested song rendering on my songs, which I have formatted differently to you) as I rarely project.

**Comment by thebigg73** [comment]
<img width="540" alt="image" src="https://user-images.githubusercontent.com/7831274/228305989-058ea689-ada5-468f-a3f6-757d84876a80.png">

**Comment by thebigg73** [comment]
I've added the 'capo key' to the display.  No hands needed if autohide is switched off!

**Comment by thebigg73** [comment]
I've added the full info to the title bar (so it shows) and truncates the title bar
<img width="541" alt="image" src="https://user-images.githubusercontent.com/7831274/228310445-707f3117-f9c2-4f81-99a9-9e4915040362.png">

**Comment by iv-gha** [comment]
Looks great.
I just cannot figure out how to control the padding on left and right of our added title and click bit.  It just decides for itself -  put layout bounds on and watch the theme alter the padding sizes if you adjust the bar custim margin.  Sometimes all left sometimes all right!  Padding changes on rotation! It is irritating to not be able to remove it and use the space in our views.  Setting all 'inset' values in the xml of our middle bit makes no difference.  v5 did not have the left button and that might be the difference. Or perhaps a different theme? It is irritating not to be in control of the space before the right buttons.  Rant over.

**Comment by thebigg73** [comment]
I think I've fixed the toolbar margins and paddings
The margins around the navigation/menu button had to be set
programmatically.
The menu item (settings cog) is set via a style entry.  I've set the
padding to 0dp, but the min width to 48dp to match the others.  These
should be in the last few commits.

**Comment by thebigg73** [comment]
<img width="553" alt="image" src="https://user-images.githubusercontent.com/7831274/228369630-92df4244-2a3e-4002-b39b-a88d9c9b2043.png">
Gained a bit of space around the navigation home button

**Comment by thebigg73** [comment]
Reducing the minWidth in the styles 'ActionButtonStyle' can reduce the space taken by the menu item
<img width="542" alt="image" src="https://user-images.githubusercontent.com/7831274/228370016-0c37b328-e6c9-4a39-98c5-a0d96c49e618.png">

**Comment by iv-gha** [comment]
Initial look...  many more dp in use!
Please also add the capo menu bar view into the code that does hide/unhide of elements when moving to and back from a settings page.

**Comment by thebigg73** [comment]
That should already happen?  I added the update toolbar call in the
MainActivity back in (I think you had removed it stating it was dealt with
at song load) as it was often blank when putting the app into pause state
(opening another app then returning).  This update of the title is also
called during the song load pass and on the main activity when the song
title is set.

**Comment by thebigg73** [comment]
Ah, no, I see what you mean - I thought you meant it wasn't showing
again on returning to a song, but the issue is it isn't hiding on opening
the settings.  I'll sort that.  I'm looking at a way of sorting the layout
of the title bar to pull the key/capo to straight after the title (if it is
short enough), but still cause it to fully display if the song title is
wider.  Currently the key/capo appears at the far right next to the battery.

**Comment by thebigg73** [comment]
Fixed this by changing the toolbar layout to a constraint layout.  Rather
than just hiding/showing the batteryholder, I've had to also hide/show the
contents of these as well (as I wanted to try and avoid nested views in the
constraintlayout).
Updated in the latest commit.

**Comment by iv-gha** [comment]
This has crept a  little away from the #/b issue.   If I compare (using connect) render on v5 and v6 for Capo transposed chords then user preference settings for #/b are not respected.   Choosing preference Bb over A# does not mean the transpose  displays Bb, it displays A#. 

The Transposed key/ transposed chords need to respect the users chords #/b display preferences. 

Also, v5 had a quick change to using # and quick change to using b option that is not in v6?  I guess it must take into account the users choice of native or capo display - applying to what is in use at the time. I never used it - but it is there.

**Comment by iv-gha** [comment]
I have split off the Action Bar work as that need to be progressed separately.

**Comment by iv-gha** [comment]
This remains broken at Beta 12.  Transpose does not respect the users preference choices of b/#.

**Comment by iv-gha** [comment]
This is not fixed.

**Comment by iv-gha** [comment]
Here is the chord choice settings and the resulting Capo renders - v6 and then v5.  You can see v6 does not respect the choice to show Ab etc.
![Screenshot_20230408-162617~2](https://user-images.githubusercontent.com/68599243/230730065-c99dc599-16d7-45c8-8807-29a04d4af11d.png)
![Screenshot_20230408-162252~2](https://user-images.githubusercontent.com/68599243/230730071-7293f2b1-8882-4b3f-97a6-b1aecb6f8b42.png)
![Screenshot_20230408-162459_042510~2](https://user-images.githubusercontent.com/68599243/230730079-a8fd4ac4-ee4e-4f78-9439-31e995c7e440.png)

**Comment by iv-gha** [comment]
Added a fix to #222 that might have fixed this.  Please check.

**Comment by thebigg73** [comment]
I don't know if I have been looking at different stuff, but I couldn't see this error happening as you described.  Anyway, tested your fix and it seems to function as expected.
Yes, I removed the option for force flats/sharps as this was in v5 way before specifying chord preferences and was how the desktop app coped with flats/sharps in a song.  I haven't put this back in (although as you spotted some od the variables 'forceflats', etc. are still there) as I think the chord preference is a cleaner and more consistent way of dealing with it.
What is your feelings on this?

**Comment by iv-gha** [comment]
It is what capo keys are displayed,  in the example it needs to render capo key Ab and not G#, because that is what the user prefers.  Hopefully fixed.

The manual 'to b' or 'to #.  affects the native chords.  So a song arrives in G#  but the user wants Ab - 'to b' will update the native chords.  So these options are not capo  transpose related.  (v5 does it but does not change the songs key entry to match - a bug.)

So these may be needed as part of helping the user convert songs.

**Comment by thebigg73** [comment]
Chords can be converted to flats/sharp by transposing by 0 and making sure the key preference is what they want, so safe to leave out the make flat or sharp buttons.

**Comment by iv-gha** [comment]
Yes, I saw that too.  We might come back to this - a 'Change to preferred
key' option might be a more obvious feature to add at some point.
Cheers.
