### ISSUE TITLE
v6 Beta - Orientation change faults

### ISSUE THREAD

**Issue by iv-gha** [thebigg73/OpenSongTablet#204]
Data:
Orientation change is permitted when the device global orientation setting is set to fixed - odd.
Orientation change leads to a layout with incorrect custom margins and song view incorrectly positioned. 
This can cause
 - Bottom clipped song
 - Differing layouts of song on initial open  and after rotate away and back to the original orientation.
 - Jumps of songs if scrolled (as the layout corrects).
An open drawer may not be closed on orientation change.

**Comment by iv-gha** [comment]
I am working on fixes for this for the v6 app - issues spotted whilst working on ActionBar animation glitches.

**Comment by iv-gha** [comment]
I have put up a pull that addresses all Action bar issues and custom margin issues on rotation.  I have not addresses stopping rotation if the device is globally set to not rotate - doh!

**Comment by thebigg73** [comment]
Fixed the rotation issue (respecting user device settings)

**Comment by iv-gha** [comment]
I see the chat about edit and rotation...  an option is to not support rotate of the efit dialogs?
