### ISSUE TITLE
v6 Beta - Song menu issues

### ISSUE THREAD

**Issue by iv-gha** [thebigg73/OpenSongTablet#205]
v6 song menu usability issues -  v5 refinements missing

'Song scroll bar on right to not conflict with set click boxes'
'Set click box is also clicked by the the click of the frame containing the click box.
'Greater separation of Alphabet listing buttons giving larger click areas

Click accuracy is poor for a user using a device on a stand etc.  v5 UI has oversize click areas (generally by click actions on the containing frame) for most key click activities (song menu and main screen).  v6 is behind.

v6 search result usability issues
Data:
If the user has a small screen device and selects a number of search options and has the keyboard open few, possibly no, results are visible to scroll through and select.

This may be tricky to resolve as there is a conflict with the current design to expand active criteria at the top of the dialog - the results area is constricted.

**Comment by thebigg73** [comment]
Agreed that the search is going to be hard to resolve with multiple searches open on a small screen.  The user then has the choice to restrict his search.  Other than creating the searches within a scroll view (which I'm not keen on).

I've not found the scrollbar has even been an issue with the checkboxes for me in v6.  I know you spent a lot of time on this in v5.

I've increased the clickable padding around the checkbox (potentially at the expense of the song title/subtitle.

For the alphabetical song index, the clickable padding is determined by the font size.  This allows the best of both worlds.  I like a small index and can approximate click then scroll.  Setting the font size in the alphabetical list to a larger size (20sp) is larger than the v5 clickable area - the same height as a song menu item depending on the user font choice.  Likewise song menu items will have larger clickable areas based on the font size chosen.  I disagree with increasing the padding independently of the font size - we'd end up with huge space and tiny text if the user wanted a small font size.

**Comment by iv-gha** [comment]
UI design is certainly more difficult if the user is able to change font sizes!  The goal is to be reliable in use.

We should follow material guidance and not permit too small click areas - I think for buttons it is  48dp.  We can hope they know what is sensible!  It may look odd (in which case do not allow the small font size!) but it will be clickable!

Touch UI design is very spaced and avoids element clashes.  Low precision touch design can be even more spaced!

The touch area of a right scroll bar unusually extends invisibly to the left of it's position to support fast scroll.  It is not intended for close proximity to ticks, rather to be a side element to a simple list.  As the complex song list has a tick close to / within the fast scroll area it is a UI clash on the right of the song list.   A move of the scroll to the left sees it then extend right over the song detail.  As this is not a typical click target it is unlikely to be a UI clash and meets the scroll bars designed use being over a simple list.  The user can click on and use the scroll!  This simple change makes it work for touch.  Is there any reason to keep a UI clash?

**Comment by iv-gha** [comment]
To sell it ...  You can as also position the tick further right to maximise song details area.  No clash!

Also, the alphabet list does not have a scroll indicator - it is not useful.

**Comment by iv-gha** [comment]
I advise treating the frame an element is within as requiring click action, simply calling the contained elements click action.  Overall click area is then controlled by the frame which can have min size set to ensure clickability.  For example the entire frame of the tick area in v5  is clickable,  the tick only doing click for it's area.    Size, position etc of the tick does not affect the effective click area which is the entire frame.  This is very relevant for complex text views, by using the frame as backstop all areas with text on or not are active - this makes them more Material in behaviour.  This method is used for the Option bar song details area in my recent commit - small fonts do not make it harder to click, the clickable frame takes up the slack with it's size unchanged, each text view has its own click. Fun.

**Comment by iv-gha** [comment]
As regard v5 and v6. When I setup v6 to give base v5 usability I run out of buttons (would have to access other functions using the menu) and it gets cluttered.  Remembering v5 also has hidden and active scroll buttons. UI design is tricky!  At the moment v5 wins it for me. Doh.
![Screenshot_20230325-111806](https://user-images.githubusercontent.com/68599243/227714669-4e305116-f6b2-421b-86e9-285beeff2c70.png)
![Screenshot_20230325-112121](https://user-images.githubusercontent.com/68599243/227714679-aa8fb847-28a5-4116-b3bc-8ad2934234ee.png)

**Comment by iv-gha** [comment]
Use of fast scroll after full indexing will crash  the app.

**Comment by thebigg73** [comment]
I'm a bit confused!!

Regarding the fast scroll song index - if we move this to the left, won't it interfere with the alphabetical list?

`Also, the alphabet list does not have a scroll indicator - it is not useful.`
There is a scroll indicator to the right of the list (before the song index)?

I see the issue with the display prev/next.  v5 doesn't have the text - just the left/right arrows.  So if I remove the text that fixes the issue with that.  A shame as I like seeing the text.   I could put the up down arrows on the main page in the middle of the view, to leave options for 8 other custom buttons.  Beginning to feel like v6 is becoming v5 !!

I'll look at making those changes

**Comment by thebigg73** [comment]
> Use of fast scroll after full indexing will crash the app.

I've had this issue right from the start.  Technically recyclerviews don't have fast scroll and this was based on numerous bits of other code pulled together to implement a custom one.  The crash doesn't really give any indication as to what is causing it, making it really hard to track.  v5.6 used a listview which is poor for performance and memory, so I moved to a recyclerView.  If I comment out the scrollToPosition() action when dragging the handle, the crash doesn't happen, but the song list doesn't update.  It seems like the view isn't quite ready to scrollTo.  I'll remove the fast scroll unless you have any ideas on this.  It has been in my _TODO list file for ages and I've spent a few hours today trying to figure it out.

**Comment by thebigg73** [comment]
Disabled fast scroll
Resized checkbox clickable frame to be at least minimum size
Resized alphabetical items to min size recommended

**Comment by iv-gha** [comment]
Placed on the left the fast scroll click area extends to the right.  The
alphabet scroll bar needs to go - it is not needed.  See v5 for a nuance
that if you use the alphabet at all it turns off fast scroll.  Alphabet is
more accurate!  Next time the song menu  opens it opens reset so fast
scroll is back on.  Hopefully clearer.

**Comment by iv-gha** [comment]
What can I say, v5 is pretty good at being minimalist. Doh.

**Comment by iv-gha** [comment]
And I have caught your update!

**Comment by iv-gha** [comment]
I questioned use of fast scroll in v5 and came to the thought that it was useful when Alphabet is off.  If it cannot behave then it necessarily goes. I never use it.  Alphabet rules!

**Comment by thebigg73** [comment]
I think the fast scroll was implemented way before the alphabetical list.  It is disable for now, but I'll refactor without that custom class and revert back to a standard recyclerview

**Comment by thebigg73** [comment]
![extrasettings](https://user-images.githubusercontent.com/7831274/227737014-fff96d77-4f62-41cf-8cab-675e42ae73cf.png)

Added options to minify the prev/next buttons to not include text.  Also has the option to stop them automatically hiding.

**Comment by iv-gha** [comment]
In regard the alphabet scroll, a typo, it is not needed and keeps activating when using the song list. v5 does not have it - no one missed it!

**Comment by thebigg73** [comment]
I was confused between alphabet and alphabet scroll - clearer now!
I've update the next/prev buttons - I was having issues getting both to display properly - fixed now.  For smaller devices, the prev/next buttons if both used are best with non-text versions
FABs have extended click area too (using custom view wrapper MyFAB)

**Comment by thebigg73** [comment]
Removed the scrollbar on alphabet index too
