### ISSUE TITLE
v6 Beta - Button click areas

### ISSUE THREAD

**Issue by iv-gha** [thebigg73/OpenSongTablet#206]
Data:
Main screen button click areas are Android default sizes intended for devices held in the hand.

v5 commits have added oversize click areas for on-screen buttons (4x area ish) and very large areas for scroll and set buttons (9 x area ish).  The app is frequently used at distance with v5 optimised to reduce the demand for touch accuracy.  Accepting that v6 is different it still has an at distance use case needing click areas optimised, where possible, for this use case.

**Comment by iv-gha** [comment]
As you will know, turning on layout bounds in developer options is useful for observing layout and click areas.

**Comment by thebigg73** [comment]
I've never actually used that option before!  Still learning!

Do you mean adding larger padding around the page buttons?  I hadn't intentionally added oversized click areas on v5 - I'm asuming you did?

**Comment by thebigg73** [comment]
Looking at the code, the only difference is the useCompatPadding option in v5.  This adds more space around the button, but doesn't add extra touch space or oversized click area (i.e. clicking on this space doesn't trigger the button)

**Comment by iv-gha** [comment]
It is the same principle as being able to click anywhere on a material switch and have it click.  It is essential when removing the need for precise click, a stress that is not needed for a songbook!  My intentional commits. yes.

In v5 the scroll and set buttons are particularly big so that a stab in the approximate area of the button gets a click.  Without the oversize it requires much greater care - a much more conscious front of brain thing!  The page gesture area too was made smaller so that it never gets the mis-clicks of buttons.

The song list 'add to set' tick has the entire area around it also click active - a stab at a button that completely misses the tick will work. Scroll to a song and stab!

I suggest looking at v5 code to see how it is done - I remember assigning click actions, to call the click action of say a  button, to the relative layouts around buttons.  I think this approach best as it leaves the button as-is.  I think all key v5 buttons have oversized (my term) click areas.  It is all about usability.

**Comment by thebigg73** [comment]
I've created a custom FloatingActionButton layout for the page buttons and added an oversized clickable area.  It is intentionally slightly smaller than v5, which in my opinion is now looking quite ugly!    I'll push this shortly

**Comment by thebigg73** [comment]
![marginsv5](https://user-images.githubusercontent.com/7831274/227631876-df1263ee-0fa7-4161-912f-9981c115663f.png)
v5.6.0

**Comment by thebigg73** [comment]
![margins v6 new](https://user-images.githubusercontent.com/7831274/227632002-4c6301d2-f52e-4c71-a0f8-3ab460e01306.png)
v6.0.0. beta 11

**Comment by thebigg73** [comment]
I've also added this to the song/set + buttons.  Most other actions are not 'at a distance', so shouldn't require this.

**Comment by iv-gha** [comment]
You may not have picked up on, in v5 turning off page scroll buttons does not remove the click areas just the buttons.  Sadly v6 UI does not have this screen touch behaviour.

By way of usability feedback, there is for me a usabilty gap...

v5 has 6 v6 button actions permanently available.  Song menu, transpose (short and long press of song icon), add to set/make a variation (short and long press of + icon), scroll up and scroll down buttons (permanent on screen feature). Once I add set, pad and metronome, so three mini semi transparent buttons, I am good for rehearsal, performance and quick add and adjust of songs to a personal set when connected  - flexibility.  This still leaves lots of v5 buttons should I feel the need and those set move buttons.

I usually have only 3 small buttons on screen.

A user installing standard v5 gets lots of in-built screen buttons - they are not told.  I like the v6 help feature.

The UI choices in v6 have impacted usability sometimes better, sometimes worse.  My focus has always been on rock solid features and ease of use in performance.  I hope you will not be too offended or frustrated as I champion this.  v6 needs the love!

**Comment by iv-gha** [comment]
As mentioned, it is the frame the element is in with click actions on that
dictates overall effective click size.  The element can remain standard.
This is easy to code and generally a suitable frame is already present.

**Comment by thebigg73** [comment]
I had added the frame and collect click from that.  What I meant was I hadn't  set the frame quite as large as v5

**Comment by iv-gha** [comment]
Sounds good.  v5 is what it is.

**Comment by iv-gha** [comment]
The v5 spacing for on-screen buttons was not changed when click action was added to the containing view.  v6 gives us the change to consider a good look vs usability compromise.  Any reason why v5 made the spacing that large?

**Comment by thebigg73** [comment]
From memory I used the appCompatSpacing="true" in the xml which was used to
bring older device margins/paddings in line with modern devices and
material design.  There are still some strange issues with material icons
like FloatingActionButtons that tend to ignore margins/padding settings.
Our method of encapsulating inside a FrameLayout overcomes this.  I've got
it set so if you use the MyFAB custom view, you can set the (clickable)
padding inside the FrameLayout around the FAB using the
app:fab_padding=".." property in xml.
I'm beginning to wonder about the size of the CheckBox in the song menu.
Setting this to a minimum size of 48x48 dpi reduces the number of songs
visible in the song menu and also increases the issue of the filters
reducing what remains on screen.  There are no issues on my 10" tablet, but
my mobile phone only shows about 6 songs with 1 filter visible.  What do
you think?

**Comment by iv-gha** [comment]
Hello,  in v5 the tick sits in the entire right view with all of that clickable.  This means you can shrink the column width to a sensible size and position the tick as you want. A click anywhere in on the right sets the tick. v5  has the tick central and uses a bespoke offset white tick graphic to do that.  So add click to the right view with the tick in it.

**Comment by iv-gha** [comment]
Having put on layout bounds I see you may already be doing click on the containing view.  Is the line do-able with less padding allowing the space to be used to expand the details and click heights? Maximise those dp!

**Comment by thebigg73** [comment]
Yeah, I've removed the padding (which was there for the now removed fast
scroll).  Looks more consistent now.
