### ISSUE TITLE
V6 beta - settings icon stays as cross/close

### ISSUE THREAD

**Issue by thebigg73** [thebigg73/OpenSongTablet#208]
Not sure why but this happened....
![Screenshot_20230326-225951_OpenSongApp](https://user-images.githubusercontent.com/7831274/227807537-c4024ded-5bf5-4eee-9c8f-8503a86fda21.jpg)

**Comment by thebigg73** [comment]
Only happening on one device (tablet).  Will try reinstalling tomorrow!  Stays as settings city, but opening settings then closing quickly triggers issue.  It gets fixed on restart

**Comment by iv-gha** [comment]
It is curious as it clearly shows all other elements correctly.  That it shows a settings icon at all also shows the code to change the icon ran at least once.  Strange

**Comment by iv-gha** [comment]
No clock though.

**Comment by thebigg73** [comment]
Yeah, I hadn't spotted that either.

**Comment by iv-gha** [comment]
When I picked up the latest changes, I also am seeing this.  It appears that the order of option menu activity has changed.  A bit more thought and I have consolidated the logic into navController.addOnDestinationChangedListener - surely this must be called!  Also settingsOpen can be reliably set in the same place, removing the need to set elsewhere.  'Feels' better.

**Comment by thebigg73** [comment]
Fixed!
