### ISSUE TITLE
v6 - Performance mode wrongly strips out blank lines inside a song

### ISSUE THREAD

**Issue by thebigg73** [thebigg73/OpenSongTablet#211]
https://github.com/thebigg73/OpenSongTablet/blob/6bd39d34e88edf4e150464abfb1a5d2ed4ba148d/app/src/main/java/com/garethevans/church/opensongtablet/songprocessing/ProcessSong.java#LL1571C9-L1595C9

<img width="399" alt="image" src="https://user-images.githubusercontent.com/7831274/228603851-3ecca239-7eab-4e34-b123-212b6b67de6d.png">
<img width="361" alt="image" src="https://user-images.githubusercontent.com/7831274/228603988-a30a817e-ce12-484e-8337-1c9fc13eded2.png">

**Comment by thebigg73** [comment]
Also applies between sections with trimSections switched off - unexpected behaviour

<img width="486" alt="image" src="https://user-images.githubusercontent.com/7831274/228604752-2500fcb3-1bec-4709-984b-098d2463bfc7.png">
<img width="548" alt="image" src="https://user-images.githubusercontent.com/7831274/228604927-2bb82885-21dc-4da6-a20e-80c5a9a7139f.png">


This was masked as I had trimSections on and addSectionSpace on, so didn't notice the issue between sections

**Comment by iv-gha** [comment]
What you have is new line followed by new line?  These in v5 and v6 code are noted for processing as a section break.  So in your song they become  2 empty sections.

You get 

[V]
[]
[]
[C]

and empty sections are ignored on render. So..

[Verse]
[C]

If a blank line /n/n is in opensong song format a section break and we ignore empty sections then v6 is processing properly and v5 is getting it wrong.  

I think something like

 Line 1
 Line 2

 Line 3
 Line 4

Is expected as 2 sections.

The question is what is

 Line 1
 Line 2

                           (Multiple blank lines)

 Line 3
 Line 4

**Comment by iv-gha** [comment]
In your first example you have a section with header [C] followed by a Section with no header [].   The sections appear one below the other with no separation. There is nothing shown for the empty header.

In the second you have [C] followed by 2 [] and then [V].  Removing empty sections gives [C] followed by [V].   They render one after the other without separation. In this case you see the 'Chorus' header.

**Comment by thebigg73** [comment]
The issue is the first example ha a blank line to allow for additional space to be shown in performance mode (for notes, readability, etc.)
Both parts should appear as the chorus header in Stage/Presenter mode, however in Performance mode, I want the gap to show.

The same applies in the second example, where additional whitespace should appear at the end of a song for user choice (readability, notes, etc).  If users add extra blank lines (\n), they expect them to appear (unless they have switched on trim sections).  Currently these sections are being trimmed regardless.

I've put a potential fix in place for Performance mode (the mode I use all the time).   I've tried not to mess with Stage/Presenter mode rendering, but you are a better judge if these modes perform as intended

**Comment by thebigg73** [comment]
<img width="261" alt="image" src="https://user-images.githubusercontent.com/7831274/228964392-52d3c01c-66e4-452a-ac9a-825b3ea8848b.png">

<img width="273" alt="image" src="https://user-images.githubusercontent.com/7831274/228964504-9a14cbc1-607a-424a-ac4b-c7eab3ae5263.png">

<img width="276" alt="image" src="https://user-images.githubusercontent.com/7831274/228964612-52031758-c601-478c-9ae7-9b53037196cb.png">

**Comment by thebigg73** [comment]
The perfomance mode view (middle image) is what I would expect to show and what my last commit does

**Comment by thebigg73** [comment]
Without this fix, the Performance mode becomes unreadable with every section flowing directly into another section as was shown in my original image in the 2nd post

**Comment by iv-gha** [comment]
It is our choice to render content as we wish.

I looked at opensong, first time for everything(!), and it treats white space between sections as not to be displayed (noise),  it treats blank lines after a header and before used lines also as not to be displayed (noise).    So in terms of presentation then we may want to follow the opensong behaviour for compatibility.  In terms of display to screen then we should decide what to do with noise both between sections and after a header and before used lines.  The commit code did the opensong presenter thing.  So what is the sensible opensong app screen display rules for this noise?

**Comment by iv-gha** [comment]
The original code and my description is the opensong /n/n rule.  We might need the opensongapp screen/print and a distinct opensongapp present behaviour - this might need to be the opensong rule.  A nuance!

**Comment by thebigg73** [comment]
OpenSong does respect noise between lines for chord sheets (what OpenSongApp was originally designed to replace)
<img width="472" alt="image" src="https://user-images.githubusercontent.com/7831274/228968480-52472102-cfa4-44cb-b293-3e244e3fa4af.png">

<img width="418" alt="image" src="https://user-images.githubusercontent.com/7831274/228968529-79ad3daa-3170-4989-83e3-5cd10586e5f8.png">

**Comment by iv-gha** [comment]
We perhaps agree -try to behave like opensong. 2 render styles. Oh the quirks!

**Comment by thebigg73** [comment]
<img width="248" alt="image" src="https://user-images.githubusercontent.com/7831274/228971382-33c74d13-9cdb-4815-80fb-75c55c2f7045.png">

A compromise for Stage/Presenter Mode which keeps your sensible suggestion of splitting sections, but ignoring the empty sections cause by noise at the end of a section

**Comment by thebigg73** [comment]
Note the empty (Verse) section caused by whitespace at the end isn't included in Stage Mode now (shown above), but the split chorus is changed into section splits using the previous header.

It renders as expected in Performance mode
<img width="251" alt="image" src="https://user-images.githubusercontent.com/7831274/228971919-633ec408-2392-471e-80c2-70deb7811f89.png">

**Comment by iv-gha** [comment]
That, I think, agrees well with OpengSong behaviour.  I think of our stage mode as a different take of presenter mode - so having them handle noise the same is good.  I cannot claim to have invented header carry forward as it is the v5 behaviour for stage/presenter - v5 good stuff.

**Comment by iv-gha** [comment]
I see the need.

Whilst the latest change fixes performance primary screen I can see it has side effects on like presenter mode sections being out by 1.

Needs a tweak to get section processing good for all modes and screens - I will propose changes.

**Comment by iv-gha** [comment]
I've added pull #215

**Comment by iv-gha** [comment]
Fixing the fixes! L

The problem of removing sections with no lines, just header, is that a second screen typically has no chord lines = more sections removed = stage and presenter mode have mismatched sections.  Example, a chord only intro section is not a section on a second screen with no chords displayed.  Previously no line sections made it through.

What was removing no line sections addressing?

**Comment by iv-gha** [comment]
Had to revert removal of no line sections as breaks too much in non performance mode.

**Comment by iv-gha** [comment]
Other outputs - brief look shows print outputs also need to be looked at.

**Comment by thebigg73** [comment]
#215 
This isn't right for Performance mode.  Users would expect the space between sections to reflect the song edit window.  There now seems to be an extra line inserted?

<img width="246" alt="image" src="https://user-images.githubusercontent.com/7831274/229369716-3254d383-d531-40ce-9169-08bcc670d2a0.png">

<img width="250" alt="image" src="https://user-images.githubusercontent.com/7831274/229369736-6eb5ecc0-d3c2-4c1a-af20-49148f3e8947.png">

**Comment by thebigg73** [comment]
Ultimately extra blank lines after a section should be included in that section, not a separate section.  In stage mode/presenter mode, these extra blank lines can be removed by default, but in performance mode they should only be removed if the user has switched on the trim sections option.  Switching on the add section space then adds back in a consistent spacing between sections (currently 75% of a line height).  Stage/Presenter modes could use that logic by default

**Comment by thebigg73** [comment]
Other than the extra line, it looks good in Performance mode though

**Comment by iv-gha** [comment]
Where is the extra line? (ahh I see at end of section)  Is that added on layout?
Added - no it is in section processing.  Let me look!

**Comment by iv-gha** [comment]
Fix the fixes!  Not quite there with the last tweak. On further test not good.for other modes.  I am happy to add the replace you had.  I will pull something soon.

**Comment by iv-gha** [comment]
#217 has the fix.

How is double new line section split meant to work?  From what I see opensong does not split if double new line is in a section with header? Just trims out the blank lines and projects as a single section? Any detail?

Is this an opensongapp added feature?

**Comment by thebigg73** [comment]
For presenting, OpenSong (desktop) ignores the double line splits inside a
section and just displays this as one section (no blank lines in between).
Blank lines at the end of the song are also trimmed out.  I notice that
blank lines at the end of a section are converted into lines with a single
space added at the start so they aren't empty.
The chord sheet output (what the app is designed to replace) respects both
line spaces inside a section and additional line spaces after a section.
What you have working on the Performance Mode in the last pull request
perfectly reflects the chord sheet function of the desktop app, which is
perfect in my opinion.
The Stage/Presenter modes in the app do use the double line space as a
section split (with a carry forward header) which is different from the
desktop version which regroups into one section with no line spacing.
However, I think the current code in OpenSongApp is a good improvement for
output and think this should stay as it is now if you agree?
Given that section splits/numbers are irrelevant on Performance mode, there
is no issue of devices getting out of sequence when presenting or connected
via Nearby since Performance mode ignores sections.
Based on your last pull request, I think the Stage Mode and Performance
mode look and function great (other than Stage Mode still having the § symbol
in front of the first header.
It looks like Stage Mode is trimming the sections by default (rather than
the user setting) - is this intended? - perhaps to avoid blank sections?
If so, that is fine since section spacing can be added by the user
preference.  I think it is important to have performance mode reflecting a
chord sheet output that reflects any spacing in the file.  If you are happy
with the way Stage Mode (and by default Presenter Mode?) deals with
sections, I'm happy too.

Good work on what you've done!

**Comment by thebigg73** [comment]
That extra code seems linked to the trim sections call.  When switched on in performance mode, it also shows at the top (and stops the heading being beautified)

<img width="274" alt="image" src="https://user-images.githubusercontent.com/7831274/229379102-c1996c2d-9a91-4610-8c9c-9c0ed5ad63da.png">

**Comment by iv-gha** [comment]
Pull added.

I've just setup v5 for no trim and it is v.bad at displaying blank lines in performance mode. I always trim so did not see this.  Was this issue raised by a beta tester?

**Comment by thebigg73** [comment]
Yes - a beta tester who still uses v5 pointed out the Performance mode
issue with line spacing while he was testing out beta.  I always have 'trim
section space' and 'add section space' switched on, so I hadn't noticed
this either!

This beta tester also gets some very strange quirks when he tests the app -
two in particular I can't figure out for him is he reports when he scrolls
on the edit song window (the MAIN tab), all of the drop down menus open
up.  Also, the actionbar doesn't begin to autohide until he taps on the
screen.  I've had real issues trying to replicate these ones, so I was glad
when he pointed out a bug that he saw that I could replicate on all my
devices!   I haven't used v5 of the app for well over a year now (other
than pulling your fantastic updates onto the Android Studio emulator to
test before releasing), so can't really comment on how that handles song
processing!

**Comment by thebigg73** [comment]
By default (I think) v5 defaulted to switch on section trimming and adding
spaces maybe?
