### ISSUE TITLE
v6 Beta - Font choices

### ISSUE THREAD

**Issue by iv-gha** [thebigg73/OpenSongTablet#212]
Render does not appear to respect the user choice of fonts.

**Comment by thebigg73** [comment]
This seems ok on my devices (picked a horrible font)
<img width="276" alt="image" src="https://user-images.githubusercontent.com/7831274/228966317-08f3b476-3dba-4d71-8704-57e65303c670.png">

**Comment by thebigg73** [comment]
<img width="324" alt="image" src="https://user-images.githubusercontent.com/7831274/228966421-7af4c7fe-773b-46b9-ae8d-82948321abfa.png">

**Comment by iv-gha** [comment]
I think it is the chord font being saved by change but not used in that session.  It perhaps applies on restart. A question of getting the fonts in immediate use?

Trying to check second screen fonts using the developer mode virtual screen..  crashes the if in use and the app is opened and can crash sometimes if put on during use.  Have not looked at second screen (but know much is 'odd') as my focus is on primary screen render.

**Comment by iv-gha** [comment]
You are probably still working on this...  capo chords do not respect chords font choice.

**Comment by thebigg73** [comment]
Fixed the capo chord font - I hadn't put a check for 'capoline' line type, so it was returning the default lyric font

**Comment by thebigg73** [comment]
Fixed the second screen crash and presenter mode second screen back up and running.

**Comment by iv-gha** [comment]
Second screen info font is not used.  Change of size of info elements is not being used when  changed - fonts / size changes need to be immediately used.

**Comment by thebigg73** [comment]
Fixes
