### ISSUE TITLE
v6 Beta - second screen display (known bugs)

### ISSUE THREAD

**Issue by thebigg73** [thebigg73/OpenSongTablet#219]
Song info not always updated correctly
For Stage/Presenter mode some sections seem to trigger text wrapping over multiple lines (which is the default for a textview).  This, however, breaks the scaling.  Only occurs on text only output (no chords being displayed) when the max scaled font size is large enough

**Comment by thebigg73** [comment]
Strangely this seems to have fixed on restart of the app - will need further checking

**Comment by iv-gha** [comment]
I have seen this also with it clearing on restart.
