### ISSUE TITLE
Song durations not saving

### ISSUE THREAD

**Issue by millerthegorilla** [thebigg73/OpenSongTablet#22]
I am often finding that when I am returning to my songs, the duration of the songs has been lost.  I know the songs are stored in XML rather than database, so is there something that I need to do to save the edited song, so that I don't lose the changes that I've made?
Also, it would be nice to be able to add a couple of buttons or a slider, to speed or slow the song duration, editing and saving the new song duration as the change occurred at the button/slider.
I haven't had time to look at the code with regards to converting it to Linux yet, but I might do this weekend if I get time.  If I make any useful changes I'll submit a pull request.
Thanks for your work btw.

**Comment by thebigg73** [comment]
Dealt with in duplicate post
