### ISSUE TITLE
v6 Beta - Action bar transitions

### ISSUE THREAD

**Issue by iv-gha** [thebigg73/OpenSongTablet#221]
The latest dev version using constraint views is broken

Data:
1. Song details run under the clock information on small screens.
2. In performance/stage mode display of Actionbar settings needs to show the clock etc so that the user can see the effect if changes made.
3. The right menu button is not centred on the Action bar - the settings title should aligned roughly centrally with the icons across the top of the bar - at the moment it is to far down the screen.
4. Presenter mode does not require the song details information. - transitions in this mode currently flash these details.  Updates at the top level in presenter mode need to cleanly display 'Presenter mode' 

Due to the complexity of the opensongapp action bar it may be found that constraint views are difficult in use.  The song details block and the settings title must align well on the action bar and this appears difficult with constraint views.  We may need to revert to the previous design.

**Comment by thebigg73** [comment]
The song title doesn't run behind the clock/battery block in constraint layout.  The song author did - fixed this

**Comment by thebigg73** [comment]
No key set
<img width="528" alt="image" src="https://user-images.githubusercontent.com/7831274/231760352-ef820bfb-fae3-4fe8-954c-a292ba7cddd6.png">

**Comment by thebigg73** [comment]
Unfortunately without constraint layout the correct positioning of title, key, capo key and allowing ellipse of the title is virtually impossible - this never worked on v5 as far as I can remember.
I'll fix all of the above

**Comment by thebigg73** [comment]
Should all be fixed - let me know if not!
