### ISSUE TITLE
v6 Beta -  Second screen

### ISSUE THREAD

**Issue by iv-gha** [thebigg73/OpenSongTablet#233]
A start at looking at Second screen...

Data
1.  Presenter mode is not adding space between sections.
2. A move from presenter to other modes will cause unwanted line wrap in the new mode.
3. Stage / Presenter layout is missing top and side border spacing. v5 behaviour is to not layout to the edge but away from the edge within the background.
4. v6 negative/positive margins can cause uncentered layout.
5. Capo info should  align with the text border (once 3 is sorted).
6. Bold of lyrics is missing.
7. Block shadow does not function.
8. Second screen layout should correctly redraw after changes are made in second screen settings - so user can assess the result.

**Comment by thebigg73** [comment]
Can I clarify

> 1. Presenter mode is not adding space between sections.

Is this when displaying on the second screen or on the main device?  Presenter mode (as with Stage Mode I think now) shouldn't have section spacing (empty lines) as the secondary display doesn't use this as only one section is ever on screen at a time, so blank spacing between lines has no purpose. I think I might be misunderstanding you.

**Comment by iv-gha** [comment]
Sure, no problem.  It is the full song 'print style' display used in
performance mode on second screen  -  it (I assert) needs inter section
spacing.  My mind now thinks to check exports for any section spacing
issues - as this would use similar logic.

Kind regards

All of these comments are when using one device and this devices second screen.

**Comment by thebigg73** [comment]
Ah ok.  Yes there should be section spacing on this and I can see it isn't there.  This second screen should be using exactly the same logic as the main device screen for performance mode (i.e. drawing, measuring and scaling) but with the dimensions of the available second screen size.  I've obviously missed the spacing out - this might be a legacy issue we had with section spaces disappearing in Performance mode when enhancing Stage Mode.  I'll investigate.

**Comment by thebigg73** [comment]
Can you give steps to reproduce point 2?

**Comment by thebigg73** [comment]
Point 2: Can't reproduce - any tips on reproducing?
Point 6: Which bold text setting isn't working?

All other issues fixed

**Comment by iv-gha** [comment]
Point 2
Darn it - I meant performance...
Open Stage mode.  Display a section with a long line on second screen.
Open performance mode.
Return to Stage mode. Display the long line section.  Second screen wraps?

**Comment by iv-gha** [comment]
Point 6.  The second screen option to bold second screen lyrics.

**Comment by thebigg73** [comment]
Fixed point 6.  I still can't replicate point 2, but I did make a call in updates for other issues to initialise the presentation screen more systematically.  This may have fixed it?  Do you still see this on your devices Ian?

**Comment by iv-gha** [comment]
I will take a look. If you are explicitly setting/controlling wrap behavior
then we can be certain.

**Comment by thebigg73** [comment]
I think the wrapping was being caused by wrongly set widths on text views.
