### ISSUE TITLE
v6 beta - Autoscroll enters confused state when app resumes

### ISSUE THREAD

**Issue by iv-gha** [thebigg73/OpenSongTablet#240]
Data:
If the app is running an autoscroll and is then paused and resumed autoscroll beomes confused.  The scroll is stopped but the on screen info display remains present with the app still considering autoscroll active.  Autoscroll needs to then be stopped before it can be started.

I suggest autoscroll is stopped in onPause.

**Comment by thebigg73** [comment]
Done
