### ISSUE TITLE
Exiting the app via the back button doesn't work

### ISSUE THREAD

**Issue by ZsigE** [thebigg73/OpenSongTablet#25]
Very minor issue, but thought it was worth mentioning - if I try to exit by pressing Back, it pops up the "are you sure you want to exit" warning, but if I tap the tick icon it just restarts the app.

**Comment by thebigg73** [comment]
I've not been able to replicate this issue.  Are you using the latest version?

**Comment by ZsigE** [comment]
I was, but after the tried-and-tested IT fix of "turn it off and on again", it's working fine. Probably some odd memory issue that just needed a reboot!
