### ISSUE TITLE
Chords are not properly aligned when using multiline verses

### ISSUE THREAD

**Issue by Cryszon** [thebigg73/OpenSongTablet#251]
Using multiline verses makes normal sections' chords misaligned. This is probably because normal sections' chords are padded to accommodate the verse number indicator regardless of whether the section has multiple verses or not.

Here are two screenshots that illustrate the problem:
![Screenshot_20231124_160421_OpenSongApp](https://github.com/thebigg73/OpenSongTablet/assets/5220970/fbec7769-2362-4e82-8880-02722b7874e7)

![Screenshot_20231124_160441_OpenSongApp](https://github.com/thebigg73/OpenSongTablet/assets/5220970/23472d9a-b7a6-49ac-b940-79a7bd6c333f)

**Comment by thebigg73** [comment]
You are exactly right with the reason behind that bug.  I've added a fix
for the next release that checks for wrongly formatted 'non-multiline'
sections.
[image: image.png]

Thanks for alerting me to the bug!

Gareth
