### ISSUE TITLE
lost times from my xml when opensong updates

### ISSUE THREAD

**Issue by millerthegorilla** [thebigg73/OpenSongTablet#35]
Hi Gareth.  I keep losing song times from the xml when the program updates.  I'm sitting at the pub fuming cause i got up to play, set my gear up and opensong had updated and I've lost all my times from the xml.
I'll look at the code later this week and see if I can do something about it, but I think I might build in a database adapter so that my songs are better protected.

**Comment by thebigg73** [comment]
Sounds like you have two storage locations and after the update it is
switching to a different location.  ah update to the app won't go through
all your XML files and remove the times

**Comment by millerthegorilla** [comment]
yh.  I can't imagine what's doing it other than potential malignant hacking, perhaps a sed command of some kind on a cron schedule or a random virus.
Other than that perhaps the additions are stored somewhere, so that when I add a time, it is stored for undo, and when updating an exception is thrown in that structure and some form of stack unwinding is deleting the times.
But the phenomenon is real, and it keeps happening either way, so I'll look into coding a database adaptor, because its a safer way of doing it, with regards to hackers and any programmatic issues that might happen.

**Comment by thebigg73** [comment]
Unfortunately a database adapter is going to stop the compatibility with
the desktop version of OpenSong - something that I want to maintain.
The times are stored directly as a element in the xml file
<mDuration>....</mDuration>
When you add a time to a song, you can directly view the xml file in a text
editor and see if the line is there.  Check again if the time 'disappears'.
I'm assuming you don't have synchronisation (via Dropbox, etc.) that is
always preferring the version from the source other than the Android device?

Gareth

**Comment by millerthegorilla** [comment]
That sounds like a sensible idea thankyou.
