### ISSUE TITLE
improve usability (and collaboration)

### ISSUE THREAD

**Issue by hohwille** [thebigg73/OpenSongTablet#36]
Hi @thebigg73,
sorry, but I did not find another way to get in touch easily. I am a experienced Java developer and already open-source activist on github (m-m-m, oasp, devonfw, mojohaus, thanktoken, etc.). Besides I am a guitar player and love to sing. I just got a new tablet and tried several apps for playing guitar with focus on chordpro format, autoscrolling, etc. Most apps have annoying advertisement. I do not mind to pay some money for a nice app but most where still not that convincing or they were extraordinary expensive (I found it ridiculous to pay a monthly fee of 5€ for a simple guitar app). Now I found your app and figured out that it is open source. As it is already perfectly doing things right and solves most of the problems and features, I thought I could collaborate and contribute to your project. As I already made some bad experience with PRs that got ignored (on purpose) I therefore would like to get in touch and ask if you would be happy welcome improvements and collaboration for your project.
As a first feedback I found several great features un-intuitive and complex to use (auto-scrolling) or thought others where lacking even though they are present but just hidden in the deep feature menus (transposing). 
Also if you want to hear more feedback about usability, I often clicked on some feature that showed some kind of "half-screen overlay popup" (e.g. when clicking on the "note" icon in the toolbar). Instead of clicking the red X button to close the "popup" I clicked the android back button what opened another "popup" with "are you sure you want to exit the app?". As I did this several times I realized it would be more intuitive if the back-button in this state would close the "popup" (just like the red X button).

So enough talking right now. In case you are interested in collaboration, just drop me a mail to "joerg" at "j-hohwiller" dot "de". If you like I could try to create a PR for the suggested back button improvement. Or I could file various small issues for such observations and improvements (I do have more of them).

So far already thanks for your big effort to develop this great app. As a fan of OSS I really appreciate that you are sharing all this for free!

Cheers
  Jörg

**Comment by joke24** [comment]
Hi, I'm also interested in contributing to usability. 
Would it make sense to join forces and create a list with improvements?
I'm not a developer, but I'm working in the IT, I could share experience from using the app in my band and maybe some technical thoughts.

**Comment by thebigg73** [comment]
Go for it!

**Comment by hohwille** [comment]
Thanks for getting in touch. I will close this issue and instead create new, concrete issues to work on.
