### ISSUE TITLE
Usability: behaviour of back button

### ISSUE THREAD

**Issue by hohwille** [thebigg73/OpenSongTablet#37]
OpenSongTablet has some kind of screen overlay popups.
If you click the "note" symbol from the toolbar you get this overlay popup:
![screenshot_20180620-135630](https://user-images.githubusercontent.com/1923119/41657142-acec0b74-7492-11e8-9901-1eaf178eeb08.png)
If you click the menu button from the toolbar you get this overlay popup
![screenshot_20180620-140634](https://user-images.githubusercontent.com/1923119/41657391-8fe93bae-7493-11e8-8333-6d6768c0fb9c.png)

Now my expectation as a user would be that the back button would close these overlay popup. However it instead asks if I want to close the app:
![screenshot_20180620-135804](https://user-images.githubusercontent.com/1923119/41657478-c59da348-7493-11e8-95b4-62ea00182f7e.png)

**Comment by hohwille** [comment]
Interesting is that there are also popups that are centered on the screen like this one where the back button closes the popup.
![screenshot_20180620-140603](https://user-images.githubusercontent.com/1923119/41657935-37d4d4f8-7495-11e8-85f3-b205fc778659.png)

**Comment by thebigg73** [comment]
This is an Android DrawerLayout for the left/right song and settings menus.  Code could be added easily enough for the back button to close these first if they are open before trying to exit the app.
