### ISSUE TITLE
Usability: Autoscolling

### ISSUE THREAD

**Issue by hohwille** [thebigg73/OpenSongTablet#38]
OpenSongTablet offers a nice and smooth auto-scrolling feature. 
To activate it you need to
* click on a icon button from the right overlay icons
![autoscroll-icon](https://user-images.githubusercontent.com/1923119/41658191-f01bc9d6-7495-11e8-94b2-5cb705dea9a6.png)
* this opens a popup where you can set the values for the autoscrolling
![screenshot_20180620-142828](https://user-images.githubusercontent.com/1923119/41658314-472fd9e2-7496-11e8-8d49-5f898549746d.png)
* you need to click on the start button to start the scrolling.

In order to stop the autoscrolling you need to again
* click on a icon button from the right overlay icons
* in the pop you need to click on the stop button.

Further, you can set the defaults for auto-scrolling when editing the song. However, initial defaults are empty. Even a song duration of 200 (or whatever) would be a better default than nothing. Also from the auto-scoll popup you can not update the auto-scroll values saved with the song.

Suggested behavior:
* I would like the overlay icon for the auto-scrolling to look like an arrow down (instead of the icon that is typically associated with the self-timer of a camera).
* I would like the overlay icon to immediately start the auto-scrolling and then change its appearance (e.g. invert the icon).
* I would like to stop the auto-scrolling by clicking on the (inverted) overlay icon again.
* I would like the default values for auto-scrolling to be initialized (what ever suits you best. My suggestions delay: 10 sec, duration 200 sec).
* To edit these auto-scrolling values the existing song edit popup is IMHO just fine. However, it would also be possible to have some gesture (double-click or slide the auto-scroll overlay icon) to open the auto-scroll popup and then where you could edit only the auto-scroll values of the song.

You would loose the ability to do auto-scrolling without changing the values in the song, but actually I do not see any value in that. You typically want to configure the things for the song once with trial and error and then you got it right. 

Maybe some user might have the use-case to play a song faster some time but not in general. However, for that feature I would create a separate story where you introduce a general "speed slider". Personally I do not have this use-case and would not implement it unless requested for good reason.

**Comment by thebigg73** [comment]
In the settings menu, you can set the defaults autoscroll times and set whether you want the app to use these when it encounters a song that hasn't been set.  Otherwise the set time box is shown.

Long pressing the autoscroll (and pad and metronome) button can be used for quick start/stop if the values are set.

**Comment by hohwille** [comment]
Thanks for the hints. This is helpful. However, I still see a usability issue here and I asked several users and gave the app to new users that never used it before. Many users considered the current behavior as not intuitive. Further doing a long-press of the quick launch button is also very tricky as you often accidentally swipe out the menu or it is simply not working for whatever reason.

My suggestion for an easy improvement is that a single click on the autoscroll button will start/stop the autoscroll and only pressing the button for a longer time will open the popup. Further defaults for autoscroll should be pre-configured by default so autoscroll is always working at least somehow with a single click.

As a nice to have improvement the app could even do some smart guess for the timings if unset by counting the words and the chords of the song. But for me a simple default like 180 secs would already be enough.

**Comment by iv-gha** [comment]
Recent releases,5.2.x onward, have moved buttons away from the right edge - this reduces unintended swipe in of the right menu

Starting actions is intentional. - a long press or a short press and use of the start/stop. It, at least initially, can feel odd but has, for me, strong benefits of never allowing accidental starts - so no embarrassing starts of pads!

Current release has option to use a default autoscroll time with initial time of 180s.
