### ISSUE TITLE
Usability: overlay icons and quick launch icons

### ISSUE THREAD

**Issue by hohwille** [thebigg73/OpenSongTablet#39]
OpenSongTablet shows 6 overlay icons on the right that allow specific things.
Of course the demands and needs of what a user would like to have here with just one click may differ.
Nice is that OpenSongTablet already supports quick launch icons (http://www.opensongapp.com/user-guide/controlling-opensongapp-with-gestures-and-pedals/quick-launch-buttons)

However, with this approach you:
* first have to find this feature
* has to configure the quick launch icons
* when using this he has to always at least quick twice as he first needs to click the 6th button to open the quick launch icons and then click one of the 4 quick launch icons he configured earlier.

Of course this issue is really a nice to have but IMHO it would be better to not have the 6 overlay icon buttons "hardcoded" but instead allow the user to simply configure these directly and customize as he likes.

Further it might make sense to ask the users what are the most typical demanded things to have as overlay icon buttons by default.

For me editing the song is a feature I need very much. IMHO I do not see why this background music generation is so famous to get the 2nd icon button. As a guitar player I also like to transpose but that might not necessarily have be there by default (singers might never need it).

**Comment by thebigg73** [comment]
Agreed that there are lots of button options, but from experience of feedback, everyone has a different preference of what buttons they want to see.
You can un-group the buttons and then show or hide each as required.  This means only one click is required.

**Comment by hohwille** [comment]
Of course it is fully up to you to keep everything as is, but to improve usability and make things way easier I would suggest to simply have a single list of quick launch icons where the user can add, remove and reorder the actions.
The current implementation is of course more flexible with the different groupings but it took me hours to figure out how this is working and things could be so much easier.
In case you do not close this as wontfix consider it as a low-prio enhancement request.

**Comment by thebigg73** [comment]
I agree.  Would it be worth putting a 'settings' page button on screen to
allow users to quickly edit which ones are visible?

**Comment by iv-gha** [comment]
On screen button settings have been gathered to one place in the menu as of 5.2.6.  This may make finding button and setting custom buttons easier. 'Menu>Display>Page Buttons'.
