### ISSUE TITLE
Transpose feature should distinguish between changing view or song

### ISSUE THREAD

**Issue by hohwille** [thebigg73/OpenSongTablet#40]
OpenSongTablet has the ability to transpose a song. However, if I am not mistaken, it always immediately modifies the chords (I not yet tried having partiture/scale but assuming that would also be transposed) in the song.

As a nice to have feature I would propose the following improvement:
* When transposing you should have the option to either change and persist the entire song (current behavior) or only change the view in a transient way. This way you could transpose a song just for the moment because you are playing with others that use a different key but you would keep the original key and would do so next time when on your own.
* This could be done in the transpose popup 1. by an option (e.g. checkbox or better radio-buttons) or 2. by two alternative buttons
* Also this could be done such that the transpose popup from the overlay icon button would always do a transient transpose of the view while when editing the song there would be a new option to transpose what instead changes the song data persistently.

For the moment I would like to leave this open for discussion and await some feedback. Once multiple users agreed on a common solution this may be ready to be implemented.

**Comment by thebigg73** [comment]
This feature already exists for sets - it is done by adding a song to a set, then from the set menu selecting set item variation.  This allows the variation to be modified in anyway desired without affecting the original.  It also allows variation items to be shared as part of the set

**Comment by thebigg73** [comment]
In MaterialApp: Songs can now be saved to sets with a 'preferred key'.  When a set is loaded, if the song on the user device is in the wrong key (and a key has been set obviously), the app will temporarily transpose it for display, leaving the original untouched.
