### ISSUE TITLE
Transpose should show base chords of the song as preview

### ISSUE THREAD

**Issue by hohwille** [thebigg73/OpenSongTablet#41]
OpenSongTablet has a nice feature to transpose a song.
As a nice to have but cool improvement I would suggest:
* the app scans the song to build a `Set` of base chords (strip off all chord variants except for the base-tone and the major/minor scale, so from the chords `Am`, `Amadd9/B`, `Csus4`, `F/E`, `C` the resulting Set would be `Am`, `C`, `F`)
* in the transpose popup this Set of base chords is displayed
* when transposing up or down (using the slider) you would get a preview of how these chords change accordingly.
* maybe even the original chords remain so the app would show something like `Am --> Bm`, `C --> D`, `F --> C`

Really not high priority but guitar beginners typically often search for a setup with most easy chords (open chords like `Em` rather than `Ebm`). Even more nice to have and advanced would be an option to suggest the transposing(s) for the easiest chords resulting from that.

**Comment by thebigg73** [comment]
It does do this for the key of the song, if that has been set.
