### ISSUE TITLE
Improve touch sliding guesture recognition

### ISSUE THREAD

**Issue by hohwille** [thebigg73/OpenSongTablet#42]
OpenSongTablet has an awesome song view showing the lyrics, chords, background highlighting of intro,verse,bridge,chorus, etc.
Of course it also supports to scroll this view by touching and sliding the screen with your finger.

For some strange reason OpenSontTablet does not recognize these touch gestures as well as other guitar apps. E.g. when I touch and slide quite short and fast, OpenSongTablet often does not scroll at all. In apps like GuitarTab or GuitarSongs this however works as expected and scrolls entirely to the next "page".

Maybe there are technical reasons for this that can not be changed easily. In such case this issue may be simply closed as won't fix. However, maybe this is just a small kind of bug that can be fixed what would be great. In general the touch sliding works fine though. However, while you are playing guitar and singing (without a foot pedal and without auto-scrolling or the wrong auto-scrolling speed or because the song data is bad and just says "repeat chorus" so you have to scroll back up to there) you sometimes want to fast and quick scroll and then it is not so nice if your gesture is not recognized. This is just my feedback as a Samsung Galaxy Tab A 10.1 user. You may toke it or leave it. I will also do some analysis and dig in the code but this is really not my issue to start with and also I assume that the gesture recognition actually comes from android OS and is not coded in the app. So maybe just because of some custom logic to detect the sliding of the left and right overlay popups and the clicking of the overlay icons is causing that effect.

**Comment by thebigg73** [comment]
This is based on Android code, but is an issue due to different screen resolutions and sizes.  There is an option in the gestures and menu settings to allow users to adjust the sensitivity of this to best suit their device.

**Comment by hohwille** [comment]
e.g. when auto-scroll is active and you are scrolling up again the app behaves really bad. As other apps like GuitarSong are able to do this smooth I guess this can be fixed/improved with some deeper understanding of androids scrolling behavior and also syncing with the async task doing the auto-scrolling. Not high-prio. I might give it a try for a fix some day...

**Comment by iv-gha** [comment]
As of 5.2.x autscroll 'jumping' has been addressed.  Touch and drag will stop autoscroll.  It resumes from the stopped position 2s later. Also autoscroll stops 4s after the song is positioned at the bottom - this means drags that only temporarily position at the bottom do not stop autoscroll.  I think this is fixed.
