### ISSUE TITLE
Bug: Song chaos after getting song in new folder

### ISSUE THREAD

**Issue by hohwille** [thebigg73/OpenSongTablet#44]
I have put a lot of energy in my song collection and kept all songs in the `MAIN` folder. Also I had created a folder called `Christian`. Now I imported a song from ultimate guitar archive and choose the target folder `Christian` for the first time. As a result my song collection is now entirely broken and messed up:
![screenshot_20180623-175229](https://user-images.githubusercontent.com/1923119/41811407-48d1ed64-770f-11e8-81ae-ea02d7485bff.png)

It is not that my songs are gone in this case. After entering the search and going to an existing song everything looks good again.

**Comment by iv-gha** [comment]
Is this still bad?

**Comment by thebigg73** [comment]
Not since moving to an SQL databse
