### ISSUE TITLE
Bug: Popups closed and layout reinitialized if bluetooth keyboard connected/disconnected

### ISSUE THREAD

**Issue by hohwille** [thebigg73/OpenSongTablet#45]
When I am in a popup (e.g. editing song) and my bluetooth keyboard gets connected or disconnected, then the popup is closed and the app is reinitialized. Therefore my edited data gets lost.

**Comment by hohwille** [comment]
As I can not easily reproduce this with emulator/debugger: Do you happen to have a hint which event/method could be the entry point for this effect? I guess the UI somehow has to be reconfigured between virtual touch keyboard and physical one. However, I would have guessed that android would handle this automatically without the app to take action.

**Comment by thebigg73** [comment]
Usually these types of changes are handled by Android unless they are
specified in the manifest as being app handled.
I have declared this in the manifest for FullscreenActivity and
PresenterMode, but not for StageMode.

If the app handles them, they should call the onResume() method.  You could
try putting a logcat statement in there to let you know of that method is
getting called.
