### ISSUE TITLE
Propose logo

### ISSUE THREAD

**Issue by mirzazulfan** [thebigg73/OpenSongTablet#47]
Hi @thebigg73 . I'm a graphic designer and an open source enthusiast. I would like to contribute to your awesome project by proposing logo design for it if you allow me. I'll be doing it as a gift for free to your awesome project.
Best regard. 
Mirza zulfan.

**Comment by thebigg73** [comment]
Propose away!  No promises though - I've used the original OpenSong logo up
to this point.

Gareth
