### ISSUE TITLE
Enable Midi footswitch / pedal to control OpenSongApp page / song switching

### ISSUE THREAD

**Issue by joke24** [thebigg73/OpenSongTablet#51]
Hi,

it would be so great to make the OpenSongApp to work with a Midi Footswitch / Foot Pedal.
Connection could work with USB OTG and a basic usb midi cable and for example Behringer FCB-1010. 
So I could use the foot pedal to run my pads with ableton and switch my pages with OpenSongApp.

I tried the connection and OpenSongApp already detects the usb midi cable, but I can not assign the footswitch with the App actions.  My footswitch sends undefined control changes eg. CC22 button 1, CC23 button 2.

God bless you!

**Comment by thebigg73** [comment]
This is coming in version 6 (have it working in alpha development, but nowhere near release ready!)
