### ISSUE TITLE
Local Pad Audio While Streeming

### ISSUE THREAD

**Issue by bordrboy** [thebigg73/OpenSongTablet#63]
Feature Request: 
Currently, when in stage/performances mode and casting lyrics to a Chromecast device, the Pad audio is also casted to the Chromecast device. It would be great if the audio could still be local and just the video casted. The pad casting to a Chromecast seems to be very choppy and unreliable.

**Comment by thebigg73** [comment]
Unfortunately this is a limitation of the Google Cast API.  The only way around this is to cast back to the phone (AllCast app does this).  However this sends the audio out and then back again (causing sync issues) and will further degrade your quality.
The only way to reduce choppiness/quality issues is to ensure a good WiFi connection between your device and the Chromecast.
