### ISSUE TITLE
Bug report - Floating sticky notes no longer working as of 5.2.2

### ISSUE THREAD

**Issue by iv-gha** [thebigg73/OpenSongTablet#81]
Hello Gareth,

I have noticed that floating sticky notes have stopped working for the 5.2.2 release.  Brief investigation shows expansion of the linear layout is failing - a problem with app-compat is reported.  This has only recently stopped working.

Kind regards
Ian V

**Comment by thebigg73** [comment]
Hi Ian,

There's a few things with shall bugs.  I've done some fixed tonight and
pushed to the master channel, but I've still to test them.  That's my plan
for tomorrow!

Cheers for the heads up on the sticky notes.

Gareth

**Comment by thebigg73** [comment]
Hi Ian,

I've fixed this and a couple of others.
I've also added in the text based pdf export (image one still exists too).
All changes on the master branch.

Best wishes,
Gareth

**Comment by iv-gha** [comment]
Hello Gareth,

Pdf looks good.  It will need copyright added before the copyright text -
which by convention does not contain word or symbol for copyright.
Also, the use of - rather than : on the ley line.  So that is adopts the good style used by CCLI.

Please also think if some type of 'Respect copyright - always use legally'
should be on the export selection screen.  I am thinking CCLI would want
exports reported as use of copyrighted words etc.  I know CCLI put use info on their pdfs too.  I suggest this is neded to keep users aware of their copyright responsibilities.

Have png exports changed? They appear to be treated as having a border (affecting pdfs made) in Xodo. Perhaps the old pdf code sorted the text borders before export in someway?  It has changed.

Kind regards
Ian V

**Comment by iv-gha** [comment]
Another thought.  I think you should keep the pdf black and white.  Lots of commerically privided printers used by churches will charge a higher price for a colour print. Some ink based printers will also use cheaper black inks.  So, a black separator line will keep costs down!

Kind regards
Ian

**Comment by thebigg73** [comment]
Hi Ian,

Yeah, that's sounds like a good idea regarding a copyright message.

I did change the PNG export code slightly to allow a bigger image to be
captured (it used to require full scaling as it could only capture the
screen content).  It now captures the entire scrollable view even if it is
off the page, however, the previous method of grabbing the content (a cache
area) threw out of memory errors as it maxes out at screen resolution/size,
whereas the new method can use a bigger image and then compress it in
memory before dealing with it.  I'll have a look at the canvas settings (to
see if there is a border setting I've missed).

Gareth

**Comment by thebigg73** [comment]
Fixes made
