### ISSUE TITLE
Presentation mode - file access on Android 9

### ISSUE THREAD

**Issue by iv-gha** [thebigg73/OpenSongTablet#86]
Hello Gareth,

I have found that in presentation mode files used in slides become un-openable (unless re-opened in file manager) following tablet reboot.  This fits with the Android security model that does not persist file access authorisations across sessions (maybe).

So perhaps you have some goodness put in place to access files in other modes for presentation mode too?

Kind regards
Ian

**Comment by thebigg73** [comment]
That shouldn't be the issue if the slides or their contents (images, etc) are stored in the /OpenSong/ directory which the user gives persistent storage permissions for.
I have added in a take persistent permissions flag in to the onActivityResult code in the appropriate locations that should solve this.
