### ISSUE TITLE
OnSong Set Importing Issue

### ISSUE THREAD

**Issue by christoboucher** [thebigg73/OpenSongTablet#88]
Good Day Everyone.

I am posting here as the Forum on the opensongapp.com page doesn't seem to be working properly.

We have band members that use OnSong and OpenSong in our church and moving Set lists from OnSong to OpenSong is very difficult.

OnSong Set Export files attached. There are 2. ".onsong" & ".xml"
[OnSongSetExport.zip](https://github.com/thebigg73/OpenSongTablet/files/5383650/OnSongSetExport.zip)

I have tried multiple methods in the App to import.

If I use Set -> Import Set and import the .xml file, it says success, but nothing appears in the Active Setlist.
If I use Set -> Import Set and import the .onsong file, it imports the entire set as 1 Song and does not get the cords right, etc.
If I use Storage -> Import OnSong Backup File it just gives me "unknown"

Would it be possible to import either of these files, and Added the Song to OnSong Song folder (Overwrite if existing) and Add to the current SetList. The .xml file will be the best as the Song with Cords are already in the correct format.

I have currently got OpenSong V5.2.4 (184) installed on my Samsung TabA +S-Pen.

Kind Regards
Christo

**Comment by christoboucher** [comment]
Sorry for there being 2 requests, I received a 404 error page when I submitted the 1st one, so submitted it again.

**Comment by thebigg73** [comment]
Hi
Thanks for sending the files!  I don't have ponding, so can't check.  Can I check how these are created.  I'm assuming that is an option in ponding to export an OpenSong set?  Is there an export onsong set option too?  If so can you also sent me a copy of that too.

I'll certainly see what I can do, but it looks doable.  Those sets look like multiple songs just combined.

**Comment by thebigg73** [comment]
I've got a fix in place in version 5.2.5.  I'm not promising it will work with every file, but it certainly will with the ones you sent me.  To use them, in OpenSongApp, click on Sets>Import and then select either the .onsong or the .xml file.  I'd recommend the xml file as it will produce properly formatted OpenSong songs.
The app will extract them into a sub folder called 'OnSong' in your Songs folder.

Is the .onsong set file you sent how OnSong users send sets to each other?
