### ISSUE TITLE
Profile save and load

### ISSUE THREAD

**Issue by iv-gha** [thebigg73/OpenSongTablet#94]
Newer options for bold headings in performance and presentation mode and option for a warning on Bluetooth pedal page change are not saved/restore by the profile mechanism.  These need to be added.

Load of profile restores button settings etc. However the buttons are not refreshed. A full refresh or screen (theme  fonts, buttons is required following load.

Fixes required.

Thanks.

**Comment by thebigg73** [comment]
I've added the missing preferences to the profile action (load).  Save is simpler as it copies any preferences as an xml file.  Loading requires parsing the xml file and setting the appropriate settings.

Not sure what you mean by the buttons not being refreshed.  Is this for the two preferences above?  If so, they should be ok now that they are loaded.

**Comment by iv-gha** [comment]
Found whilst testing reset and then using profile load... Button sizes, custom buttons... did not change on profile load. So I think a full screen refresh is needed after load so that settings are applied on load.

Kind regards
Ian

**Comment by iv-gha** [comment]
Closed as resolved by a subsequent fix.

**Comment by iv-gha** [comment]
Re-opened as we still need to refresh the screen fully after a profile load (as loaded settings may have affected it).

**Comment by iv-gha** [comment]
Pull #101  includes proposed fix.

**Comment by iv-gha** [comment]
v5.3.0 included fix.
