### ISSUE TITLE
BootUpCheck usability issues

### ISSUE THREAD

**Issue by iv-gha** [thebigg73/OpenSongTablet#95]
We are already in discussion - Added to track issue

The paths reported by BootUpCheck for 'Current location:' and 'Find' for the same location are different - it would improve usability to have them report the same path to give  users confidence in their selection.    On change of location the 'Current Location:' displayed can become an invalid path.

I have proposed enhancements in my dev fork.
The approach is to:
1. Hide 'technical' parts of path (like /emulated/0)
2. Change to choosing a location for an 'OpenSong folder' to reduce use of technical terms.
2. Report folder paths below device only.
Example path /storage/sdcard1/OpenSong  reports as /OpenSong (External storage sdcard1)
Example path /storage/emulated/0/OpenSong reports as /OpenSong
All elements of the reported terminal path will be select-able by the user in the file picker.

Other tweaks include adding a song count for 'Current Location:' to provide confidence of songs being available after 'Start'.

Please consider revision of BootUpCheck to improve usability.

Thanks

**Comment by thebigg73** [comment]
Pulled request - also added song count to 'found locations'
